export enum ErrorCode {
  // General Errors
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Authentication & Verification
  EMAIL_INVALID = 'EMAIL_INVALID',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  WRONG_OTP = 'WRONG_OTP',
  OTP_EXPIRED = 'OTP_EXPIRED',
  ACCOUNT_BANNED = 'ACCOUNT_BANNED',

  // User & Seller Roles
  PHONE_REQUIRED = 'PHONE_REQUIRED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  ALREADY_SELLER = 'ALREADY_SELLER',

  // Auction & Bidding
  AUCTION_NOT_FOUND = 'AUCTION_NOT_FOUND',
  AUCTION_NOT_ACTIVE = 'AUCTION_NOT_ACTIVE',
  AUCTION_FINISHED = 'AUCTION_FINISHED',
  SELF_BIDDING_FORBIDDEN = 'SELF_BIDDING_FORBIDDEN',
  BID_INCREMENT_INVALID = 'BID_INCREMENT_INVALID',
}
