export const ApiEndpoints = {
  AUTH: {
    REGISTER: "/auth/register",
    LOGIN: "/auth/login",
    VERIFY_OTP: "/auth/verify-otp",
    RESEND_OTP: "/auth/resend-otp",
    LOGOUT: "/auth/logout",
    FORGOT_PASSWORD: "/auth/forgot-password",
    VERIFY_RESET_OTP: "/auth/verify-reset-otp",
    RESET_PASSWORD: "/auth/reset-password",
    REFRESH: "/auth/refresh",
  },
  USERS: {
    UPGRADE_ROLE: "/api/users/upgrade-role",
    ADDRESS: "/api/users/me/address",
    PARTICIPATED_AUCTIONS: "/api/users/me/participated-auctions",
    PROFILE: "/api/users/me/profile",
    NOTIFICATIONS: "/api/users/me/notifications",
    RELATED_AUCTIONS: "/api/users/me/related-auctions",
    REVIEWS: "/api/users/me/reviews",
    TRANSACTIONS: "/api/users/me/transactions",
    PIN: (auctionId: string) => `/api/users/me/pin/${auctionId}`,
    USER_PROFILE: (id: string) => `/api/users/${id}/profile`,
    USER_RELATED_AUCTIONS: (id: string) => `/api/users/${id}/related-auctions`,
    USER_REVIEWS: (id: string) => `/api/users/${id}/reviews`,
  },
  MEDIA: {
    SIGN: "/api/media/sign",
  },
  AUCTIONS: {
    LIVE: "/api/auctions/live",
    UPCOMING: "/api/auctions/upcoming",
    SUGGESTIONS: "/api/auctions/suggestions",
    MY_LISTINGS: "/api/auctions/my-listings",
    WATCHLIST: "/api/auctions/watchlist",
    CREATE: "/api/auctions",
    BY_ID: (id: string) => `/api/auctions/${id}`,
    BIDS: (id: string) => `/api/auctions/${id}/bids`,
    MY_STATUS: (id: string) => `/api/auctions/${id}/my-status`,
    WATCH: (id: string) => `/api/auctions/${id}/watch`,
    WATCH_STATUS: (id: string) => `/api/auctions/${id}/watch-status`,
    REVIEW: (id: string) => `/api/auctions/${id}/review`,
  },
  CATEGORIES: {
    GET_ALL: "/api/categories",
  },
  NOTIFICATIONS: {
    BASE: "/api/notifications",
    UNREAD_COUNT: "/api/notifications/unread-count",
    MARK_ALL_READ: "/api/notifications/read-all",
    MARK_READ: (id: string) => `/api/notifications/${id}/read`,
  },
  PAYMENTS: {
    GET_BY_ID: (id: string) => `/api/payments/${id}`,
    BY_AUCTION_ID: (auctionId: string) => `/api/payments/auction/${auctionId}`,
    INITIATE: (paymentId: string) => `/api/payments/${paymentId}/initiate`,
    DECLINE: (paymentId: string) => `/api/auctions/payments/${paymentId}/decline`,
    CONFIRM_SHIPPING: (paymentId: string) => `/api/payments/${paymentId}/confirm-shipping`,
    CONFIRM_DELIVERY: (paymentId: string) => `/api/payments/${paymentId}/confirm-delivery`,
    OPEN_DISPUTE: (paymentId: string) => `/api/payments/${paymentId}/dispute`,
    GET_DISPUTE: (id: string) => `/api/payments/dispute/${id}`,
    GET_DISPUTE_BY_AUCTION: (auctionId: string) => `/api/payments/dispute/by-auction/${auctionId}`,
    RESPOND_DISPUTE: (id: string) => `/api/payments/dispute/${id}/respond`,
  },
  MESSAGES: {
    CONVERSATIONS: "/api/messages/conversations",
    UNREAD_COUNT: "/api/messages/unread-count",
    GET_MESSAGES: (conversationId: string) => `/api/messages/conversations/${conversationId}`,
    MARK_AS_READ: (conversationId: string) => `/api/messages/conversations/${conversationId}/read`,
  },
  ADMIN: {
    DASHBOARD: {
      STATS: "/api/admin/dashboard/stats",
      REVENUE: "/api/admin/dashboard/revenue",
      ACTIVITY: "/api/admin/dashboard/activity",
    },
    USERS: {
      BASE: "/api/admin/users",
      BY_ID: (id: string) => `/api/admin/users/${id}`,
      BAN: (id: string) => `/api/admin/users/${id}/ban`,
      UNBAN: (id: string) => `/api/admin/users/${id}/unban`,
      ROLE: (id: string) => `/api/admin/users/${id}/role`,
      RESET_STRIKES: (id: string) => `/api/admin/users/${id}/reset-strikes`,
    },
    AUCTIONS: {
      BASE: "/api/admin/auctions",
      BY_ID: (id: string) => `/api/admin/auctions/${id}`,
      FORCE_END: (id: string) => `/api/admin/auctions/${id}/force-end`,
      CANCEL: (id: string) => `/api/admin/auctions/${id}/cancel`,
    },
    PAYMENTS: {
      BASE: "/api/admin/payments",
      REFUND: (id: string) => `/api/admin/payments/${id}/refund`,
    },
    DISPUTES: {
      BASE: "/api/admin/disputes",
      BY_ID: (id: string) => `/api/admin/disputes/${id}`,
      RESOLVE: (id: string) => `/api/admin/disputes/${id}/resolve`,
    },
    CATEGORIES: {
      BASE: "/api/admin/categories",
      BY_ID: (id: number) => `/api/admin/categories/${id}`,
    },
    CONFIG: {
      BASE: "/api/admin/config",
      BY_KEY: (key: string) => `/api/admin/config/${key}`,
    },
    AUDIT_LOGS: "/api/admin/audit-logs",
  }
} as const;
